server:
  port: 8083
spring:
  application:
    name: oauth2-resource
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://oauth2server:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth-server?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: password
  flyway:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        enabled: false
      discovery:
        enabled: false

